INSERT ALL
  INTO cities (name) VALUES ('Alicante')
  INTO cities (name) VALUES ('Barcelona')
  INTO cities (name) VALUES ('Bilbao')
  INTO cities (name) VALUES ('Burgos')
  INTO cities (name) VALUES ('Córdoba')
  INTO cities (name) VALUES ('Gijón')
  INTO cities (name) VALUES ('Las Palmas de Gran Canaria')
  INTO cities (name) VALUES ('León')
  INTO cities (name) VALUES ('Lleida')
  INTO cities (name) VALUES ('Madrid')
  INTO cities (name) VALUES ('Málaga')
  INTO cities (name) VALUES ('Murcia')
  INTO cities (name) VALUES ('Palma de Mallorca')
  INTO cities (name) VALUES ('Salamanca')
  INTO cities (name) VALUES ('Sevilla')
  INTO cities (name) VALUES ('Tarragona')
  INTO cities (name) VALUES ('Valencia')
  INTO cities (name) VALUES ('Valladolid')
  INTO cities (name) VALUES ('Vigo')
  INTO cities (name) VALUES ('Zaragoza')
SELECT * FROM dual;